package br.com.hrc.atestadomedico.model;

public enum Setor {
	
	CAF("CENTRAL DE ASSISTENCIA FARMACEUTICA"),
	CCIH("CCIH"),
	CMH("CLINICA MEDICA HOSPITALISTAS"),
	CMHC("CLINICA MEDICA HOSPITALISTAS - COORDENACAO"),
	CEF("COORDENACAO DE ENFERMAGEM"),
	DGA("DIRETORIA DE GESTAO E ATENDIMENTO"),
	DPA("DIRETORIA DE PROCESSOS ASSISTENCIAIS"),
	DG("DIRETORIA GERAL"),
	ENC("ENGENHARIA CLINICA"),
	EP("ENSINO E PESQUISA"),
	FST("FISIOTERAPIA"),
	FN("FONOAUDIOLOGIA"),
	GA("GERENCIA ADMINISTRAIVA"),
	LB("LABORATORIO"),
	MANUTENCAO,
	ANESTESIOLOGIA,
	CBMF("MEDICOS - BUCOMAXILO"),
	CCM("MEDICOS - CENTRO CIRURGICO"),
	CLM("MEDICOS - CLINICA MEDICA"),
	END("MEDICOS - ENDOSCOPIA"),
	NEU("MEDICOS - NEUROCIRURGIA"),
	RD("MEDICOS - RADIOLOGIA"),
	TOM("MEDICOS - TRAUMATO ORTOPEDIA"),
	UAVC("MÉDICOS - UNIDADE DE AVC"),
	EMERG("MEDICOS - URGENCIA/EMERGENCIA"),
	UTI("MEDICOS - UTI "),
	TO("TRAUMATO ORTOPEDIA"),
			NAC("NAC - NUCLEO DE ATENDIMENTO AO CLIENTE"),
			NTI("NTI- NUCLEO DE TECNOLOGIA DA INFORMACAO"),
			AGT("NUCLEO ENFERMAGEM - AGENCIA TRANSFUSIONAL"),
			AMB("NUCLEO ENFERMAGEM - AMB., IMAGEM E TRANSP. DE PACIENTES"),
			CC("NUCLEO ENFERMAGEM - CENTRO CIRURGICO"),
			CLME("NUCLEO ENFERMAGEM - CLINICA MEDICA"),
			CME("NUCLEO ENFERMAGEM - CME"),
			EMRG("NUCLEO ENFERMAGEM - EMERGENCIA"),
			TOE("NUCLEO ENFERMAGEM - TRAUMATO E CL. CIRURGICA"),
			UAVCE("NUCLEO ENFERMAGEM - U-AVC"),
			UCE("NUCLEO ENFERMAGEM - UCE"),
			UTIE("NUCLEO ENFERMAGEM - UTI"),
			NGP("NUGESP"),
			NUTRICAO,
			OPO("OPO ORGANIZACAO PROCURA DE ORGAOS"),
			OUVIDORIA,
			PAD,
			RADIOLOGIA,
			RECURSOSHUMANOS,
			RH("ROUPARIA / HOTELARIA"),
			CCV("SERVIÇO DE CIRURGIA VASCULAR"),
			SS("SERVICO SOCIAL"),
			SESMT;
			
   
	private String descricao;
	
	private Setor(){
		
	}
	
	Setor(String descicao) {
		this.descricao = descicao;
	}
	
	public String getDescricao() {
		return descricao;
	}
}
